name: docker
services:
  fastllm:
    command: # tail -f /dev/null
      - sh
      - -c
      - |
        celery -A task worker -l info > log/celery.log 2> log/celery.log &
        python3.11 main.py > log/flask.log 2> log/flask.log
    container_name: fastllm-server
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/fastllm:arm_1.2.22
    networks:
      fastllm:
        ipv4_address: 172.28.1.2
    ports:
      - mode: ingress
        target: 5000
        published: "25000"
        protocol: tcp
    restart: always
    stdin_open: true
    tty: true
  minio:
    command:
      - server
      - /data
    container_name: fastllm-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek-arm/minio:RELEASE.2021-04-22T15-44-28Z
    networks:
      fastllm:
        ipv4_address: 172.28.1.5
    ports:
      - mode: ingress
        target: 9000
        published: "29000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/ictrek/workspace-docker/chatbot/minio-data
        target: /data
      - type: bind
        source: /home/ictrek/workspace-docker/chatbot/minio-config
        target: /root/.config
  whisper:
    command:
      - bash
      - /root/whisper_run.sh
    container_name: fastllm-whisper
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/whisper:arm_latest
    networks:
      fastllm:
        ipv4_address: 172.28.1.8
    ports:
      - mode: ingress
        target: 10095
        published: "30095"
        protocol: tcp
    restart: always
  ollama:
    container_name: fastllm-ollama
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/ollama_server:arm_latest
    restart: always
    command: ["bash", "/root/ollama_run.sh"]
    stdin_open: true  # ~P~T| ~G~G~F~S~E
    tty: true         # ~P~T伪~H端
    environment:
      - MAX_MODEL_LEN=32768
    volumes:
      - type: bind
        source: /home/ictrek/workspace-docker/chatbot/ollama
        target: /root/.ollama
    ports:
      - "22299:11434"
    networks:
      fastllm:
        ipv4_address: 172.28.1.9
networks:
  fastllm:
    name: fastllm
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
