name: docker
services:
  fastllm:
    command: # tail -f /dev/null
      - sh
      - -c
      - |
        celery -A task worker -l info > log/celery.log 2> log/celery.log &
        python3.11 main.py > log/flask.log 2> log/flask.log
    container_name: fastllm-server
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/fastllm:arm_1.2.27
    networks:
      fastllm:
        ipv4_address: 172.28.1.2
    ports:
      - mode: ingress
        target: 5000
        published: "25000"
        protocol: tcp
    restart: always
    stdin_open: true
    tty: true
  minio:
    command:
      - server
      - /data
    container_name: fastllm-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek-arm/minio:RELEASE.2021-04-22T15-44-28Z
    networks:
      fastllm:
        ipv4_address: 172.28.1.5
    ports:
      - mode: ingress
        target: 9000
        published: "29000"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: minio-data
        target: /data
      - type: volume
        source: minio-config
        target: /root/.config
  ollama:
    container_name: fastllm-ollama
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/ollama_server:arm_latest
    restart: always
    command: ["bash", "/root/ollama_run.sh"]
    stdin_open: true
    tty: true
    environment:
      - MAX_MODEL_LEN=32768
    volumes:
      - type: volume
        source: ollama
        target: /root/.ollama
    ports:
      - "22299:11434"
    networks:
      fastllm:
        ipv4_address: 172.28.1.9
volumes:
  minio-config:
    name: minio-config
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ictrek/workspace-docker/minio/config'
  minio-data:
    name: minio-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ictrek/workspace-docker/minio/data'
  ollama:
    name: ollama
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ictrek/workspace-docker/ollama'
networks:
  fastllm:
    name: fastllm
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
