name: chatbot
services:
  fastllm:
    command: 
      - sh
      - -c
      - |
        celery -A task worker -l info > log/celery.log 2> log/celery.log &
        service ssh start
        tail -f /dev/null
      #   python3.11 -u main.py
    container_name: fastllm-server
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/fastllm:amd_1.2.43
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
      minio:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
      mariadb:
        condition: service_healthy
        required: true
    networks:
      fastllm:
        ipv4_address: 172.28.1.2
    ports:
      - mode: ingress
        target: 5000
        published: "25000"
        protocol: tcp
      - mode: ingress
        target: 22
        published: "2222"
        protocol: tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /home/jzy/resource/deepdoc
        target: /root/fastllm/res/deepdoc
      - type: bind
        source: /home/jzy/resource/model/bge-m3
        target: /root/fastllm/res/model/bge-m3
      - type: bind
        source: /home/jzy/resource/model/marqo-fashionSigLIP
        target: /root/fastllm/res/model/marqo-fashionSigLIP
      - type: bind
        source: /home/jzy/resource/model/tts
        target: /root/fastllm/res/model/tts
      - type: bind
        source: /home/jzy/resource/nltk_data
        target: /root/nltk_data
      - type: bind
        source: /home/jzy/resource/model/faster-whisper-large-v3-int8
        target: /root/fastllm/res/model/faster-whisper-large-v3-int8
      - type: bind
        source: /home/jzy/resource/model/BGE-VL-large
        target: /root/fastllm/res/model/BGE-VL-large
      - type: bind
        source: /home/jzy/picture
        target: /root/picture
    environment:
      MARIADB_HOST: 172.28.1.3
      MARIADB_PORT: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: Mm123456
      MINIO_HOST: 172.28.1.5
      MINIO_PORT: 9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
      # OLLAMA_HOST: 172.28.1.9
      # OLLAMA_PORT: 11434
      OLLAMA_HOST: 172.28.1.1
      OLLAMA_PORT: 22299
      ELASTICSEARCH_HOST: 172.28.1.4
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: Ee123456
      REDIS_HOST: 172.28.1.6
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: Rr123456
      REDIS_DB: 0
      CHAT_MODEL: ictrek/qwen2.5:7b
      CHAT_COT_MODEL: ictrek/ds:r1_7b32k
      SUMMARY_MODEL: ictrek/qwen2.5:7b
  minio:
    command:
      - server
      - /data
    container_name: fastllm-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/minio:RELEASE.2021-04-22T15-44-28Z
    healthcheck:
      test:
        - CMD-SHELL
        - curl -i http://localhost:9000/minio/health/live
      timeout: 10s
      interval: 10s
      retries: 50
    networks:
      fastllm:
        ipv4_address: 172.28.1.5
    ports:
      - mode: ingress
        target: 9000
        published: "29000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/jzy/minio/data
        target: /data
      - type: bind
        source: /home/jzy/minio/config
        target: /root/.config
  elasticsearch:
    container_name: fastllm-elasticsearch
    environment:
      ELASTIC_PASSWORD: "Ee123456"
      ES_JAVA_OPTS: -Xms750m -Xmx750m
      cluster.routing.allocation.disk.threshold_enabled: "false"
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/elasticsearch:8.17.2
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://elastic:Ee123456@localhost:9200
      timeout: 10s
      interval: 10s
      retries: 50
    networks:
      fastllm:
        ipv4_address: 172.28.1.4
    volumes:
      - type: bind
        source: /home/jzy/elasticsearch/data
        target: /usr/share/elasticsearch/data
      - type: bind
        source: /home/jzy/elasticsearch/log
        target: /usr/share/elasticsearch/logs
    ports:
      - mode: ingress
        target: 9200
        published: "29200"
        protocol: tcp
    restart: always
  redis:
    container_name: fastllm-redis
    environment:
      REDIS_ARGS: --requirepass Rr123456
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/redis:latest
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli -a Rr123456  ping
      timeout: 10s
      interval: 10s
      retries: 50
    networks:
      fastllm:
        ipv4_address: 172.28.1.6
    ports:
      - mode: ingress
        target: 6379
        published: "26379"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/jzy/redis/data
        target: /data
  mariadb:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --max-connections=3000
    container_name: fastllm-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Mm123456
      MARIADB_DATABASE: fastllm
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/mariadb:11
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      timeout: 10s
      interval: 10s
      retries: 50
    networks:
      fastllm:
        ipv4_address: 172.28.1.3
    volumes:
      - type: bind
        source: /home/jzy/mariadb/data
        target: /var/lib/mysql
    ports:
      - mode: ingress
        target: 3306
        published: "23306"
        protocol: tcp
    restart: always
networks:
  fastllm:
    name: fastllm
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
