name: chatbot
services:
  fastllm:
    command: # tail -f /dev/null
      - sh
      - -c
      - |
        celery -A task worker -l info > log/celery.log 2> log/celery.log &
        python3.11 -u main.py > log/flask.log 2> log/flask.log
    container_name: fastllm-server
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/fastllm:amd_1.2.31
    networks:
      fastllm:
        ipv4_address: 172.28.1.2
    ports:
      - mode: ingress
        target: 5000
        published: "25000"
        protocol: tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /home/ictrek/workspace-docker/model/deepdoc
        target: /root/fastllm/res/deepdoc
      - type: bind
        source: /home/ictrek/workspace-docker/model/bge-m3
        target: /root/fastllm/res/model/bge-m3
      - type: bind
        source: /home/ictrek/workspace-docker/model/marqo-fashionSigLIP
        target: /root/fastllm/res/model/marqo-fashionSigLIP
      - type: bind
        source: /home/ictrek/workspace-docker/model/tts
        target: /root/fastllm/res/model/tts
      - type: bind
        source: /home/ictrek/workspace-docker/nltk_data
        target: /root/nltk_data
      - type: bind
        source: /home/ictrek/workspace-docker/model/faster-whisper-large-v3-int8
        target: /root/fastllm/res/model/faster-whisper-large-v3-int8
      - type: bind
        source: /home/ictrek/workspace-docker/model/BGE-VL-base
        target: /root/fastllm/res/model/BGE-VL-base
      - type: bind
        source: /home/ictrek/workspace-docker/v1000/data/nas/root
        target: /root/picture
    environment:
      MARIADB_HOST: 172.28.1.1
      MARIADB_PORT: 3306
      MARIADB_USER: root
      MARIADB_PASSWORD: Mm123456
      MINIO_HOST: 172.28.1.5
      MINIO_PORT: 9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
      OLLAMA_HOST: 172.28.1.9
      OLLAMA_PORT: 11434
      # OLLAMA_HOST: 172.28.1.1
      # OLLAMA_PORT: 22299
      ELASTICSEARCH_HOST: 172.28.1.1
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: Ee123456
      REDIS_HOST: 172.28.1.1
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: Rr123456
      REDIS_DB: 0
      CHAT_MODEL: ictrek/qwen2.5:3b32k
      CHAT_COT_MODEL: ictrek/ds:r1_7b32k
      SUMMARY_MODEL: ictrek/qwen2.5:3b32k
  minio:
    command:
      - server
      - /data
    container_name: fastllm-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/minio:RELEASE.2021-04-22T15-44-28Z
    networks:
      fastllm:
        ipv4_address: 172.28.1.5
    ports:
      - mode: ingress
        target: 9000
        published: "29000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/ictrek/workspace-docker/minio/data
        target: /data
      - type: bind
        source: /home/ictrek/workspace-docker/minio/config
        target: /root/.config
  ollama:
    container_name: fastllm-ollama
    image: swr.cn-southwest-2.myhuaweicloud.com/ictrek/ollama_server:amd_latest
    restart: always
    volumes:
      - type: bind
        source: /home/ictrek/workspace-docker/ollama
        target: /root/.ollama
    ports:
      - "22299:11434"
    networks:
      fastllm:
        ipv4_address: 172.28.1.9
networks:
  fastllm:
    name: fastllm
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
